package personal.social.enums;

public enum WebSocketEventType {
    MESSAGE_SENT,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
    MESSAGE_REACTION_ADDED,
    MESSAGE_REACTION_REMOVED,
    USER_TYPING,
    USER_STOP_TYPING,
    USER_JOINED,
    USER_LEFT,
    CONVERSATION_UPDATED,
    CONVERSATION_DELETED,
    PARTICIPANTS_ADDED,
    PARTICIPANTS_REMOVED
}
